### ISSUE TITLE
Limit of 5 to number of menu rows?

### ISSUE THREAD

**Issue by hotairforacoolbreeze** [javalnanda/JNDropDownMenu#2]
Is there a limit of 5 to the number of menu rows? If you add add more rows to the source array in the example (columnOneArray) they don't show on the drop-down menu? Thanks

**Comment by javalnanda** [comment]
The do show up, it is scrollable.

**Comment by hotairforacoolbreeze** [comment]
Thanks - that's my fault as I was running on the simulator so I was not trying to scroll!

**Comment by javalnanda** [comment]
@hotairforacoolbreeze No prob. To avoid such confusion, I have now updated menu to utilize full height of the screen. You can update the pod and check out the latest version.
