### ISSUE TITLE
Enhancement request: set column title

### ISSUE THREAD

**Issue by hotairforacoolbreeze** [javalnanda/JNDropDownMenu#5]
Hi - I have a use case where the drop down is a list of filter criteria for a list - each row can be selected or deselected by clicking on it and it has a tick or cross to indicate if it is selected (example below). I can update the row text dynamically and this works OK, but the column title is automatically set to the last selected item when I would like to be able to set it manually - with something like a function of JNDropDownMenu:
func setTitle(_ title : String, forColumn: NSInteger)
If not called it would default to the existing behaviour, but if present would set the column title to the specified value irrespective of the last item selected. 

Let me know what you think - Thanks, Phil

<img width="402" alt="screen shot 2017-05-09 at 22 37 57" src="https://cloud.githubusercontent.com/assets/15308797/25873926/304b6e5e-3508-11e7-87c2-9677aa74d765.png">

**Comment by javalnanda** [comment]
@hotairforacoolbreeze Check out v 0.1.5. Updated as per your request :)
Screenshot looks nice. Are you using unicode for tick mark and cross symbol?

**Comment by hotairforacoolbreeze** [comment]
Thanks for the super quick response! Yes, these are Unicode 2713 and 2717 for the marks. Thanks Phil

**Comment by javalnanda** [comment]
You are welcome. Hope you are finding it useful for your project :)

**Comment by hotairforacoolbreeze** [comment]
Sorry - it's not working - the column title is set when the menu is first set up but then back to the previous behaviour when a menu item is selected. I think the issue is in the line of code below where the title is reset after a selection is made...
`
func confiMenuWith(row: NSInteger) {

        let title = self.titles[self.currentSelectedMenuIndex]

        if updateColumnTitleOnSelection {
            title.string = self.datasource?.titleForRow(at: JNIndexPath(column: self.currentSelectedMenuIndex, row: row), for: self)
        }

`

**Comment by javalnanda** [comment]
Are you setting this flag to false 
` menu.updateColumnTitleOnSelection = false`
I have mentioned that in Readme in change log.

**Comment by hotairforacoolbreeze** [comment]
Doh! Sorry I missed that - it's fine now, thanks!
