### ISSUE TITLE
Method conflict with SpreadsheetView

### ISSUE THREAD

**Issue by tuononh** [javalnanda/JNDropDownMenu#8]
There are some methods conflict with [SpreadsheetView](https://github.com/kishikawakatsumi/SpreadsheetView) (I use this to display data and your plugin to choose which dataset to display). How can I use both?
`numberOfColumns` is an example.

**Comment by javalnanda** [comment]
You will need to implement protocol in separate class to avoid conflicts. Create a two separate datasource classes which confirms to protocol and assign these classes as datasource for dropdown and spreadsheet respectively instead of implementing protocol in ViewController.
